name: division
description: A simple to use yet powerfull styling widget with syntax inspired by CSS.
version: 0.7.2
author: Rein Gundersen Bentdal<rein.bent@gmail.com>
homepage: https://github.com/Natuka/division
repository: https://github.com/Natuka/division

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^0.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
